### ISSUE TITLE
Stat Wall Not Working

### ISSUE THREAD

**Issue by AdamW78** [ThunderGemios10/Survival-Games#39]
On Version 1.11.2
Running Version 0.6.5
When using /sg setstatswall, this error appears: [https://pastebin.com/ThgL0ses](https://pastebin.com/ThgL0ses)

**Comment by ThunderGemios10** [comment]
Thank you for reporting this.
I will start working on a fix.

**Comment by ThunderGemios10** [comment]
@AdamW78 Update: I have replaced /sg setstatswall with /sg addwall in the latest patch.

**Comment by Minecraftsim** [comment]
hi i cant still do it even when i do /sg addwall im on 1.12.2 and i just says survialgameslobby Failed to load message for messages.error.notspecified plz help

**Comment by Remyk1** [comment]
> messages.error.notspecified

@Minecraftsim It's because you didn't specify an arena (the command is /sg addwall \<arena\>)

**Comment by Minecraftsim** [comment]
Ohh My bad sorry

**Comment by Minecraftsim** [comment]
Also were do you find the arena name?

**Comment by Remyk1** [comment]
It's not a name but an id in the form of an integer.
It just increments the arena id everytime you make an arena, so if you only have one arena it's just 1.
Otherwise /sg getcount and then just /sg join \<arena_id\> for all the arenas id's the getcount command returns until you find the arena you want.

**Comment by Minecraftsim** [comment]
Thank you very much i have really wonted a survival games on my server
